React Calculator Logic
kwizl/calculator-react pull request #4
Opened 2021-01-25 20:39 UTC by kwizl

# Project Logic

- In this milestone, two JavaScript modules are implemented: calculate.js and operate.js These two modules will be responsible for all the calculations. There are npm packages such as `Big.js` that are used to help in calculating big numbers.

2021-01-25 21:25 UTC, Torres-ssf commented
Hello @kwizl :hand: 
It seems that you selected the wrong project name when sending the code review request. The request is related to the Milestone 4 from the Bookstore App. Please kindly submit a code review request to Calcular Project milestone 4 as I will invalidate this request related to the Bookstore App

2021-01-25 21:44 UTC, Torres-ssf requested changes
### Milestone approved :+1: 
Hi @kwizl :hand: 
Great job on this milestone so far :clap: 
But we need to make some changes before moving on :smile: 

- [ ] Please check my comments below.

Feel free to message me on Slack if you have any questions.
Happy coding :computer: 
**Sergio Torres**

2021-01-25 21:44 UTC, Torres-ssf commented on src/logic/operate.js
> +    }
- [ ] It seems the `-` symbol is missing at the if statement

2021-01-25 21:44 UTC, Torres-ssf commented on src/logic/operate.js
> +    }
- [ ] Here we need to the `x` instead of `-`

2021-01-25 21:44 UTC, Torres-ssf commented on src/logic/operate.js
> +    }
- [ ] We need to use the symbol to the modifier operator here: `%`

- [ ] Te modifier operator should turns the number into a percentage base `e.g. 95 % == 0.95`. We can achieve that by simply 
```JS
if (operation === 'x') {
      return Big((numberOne / 100);
    }
```

2021-01-25 21:44 UTC, Torres-ssf commented on src/logic/calculate.js
> +    return {
- [ ] We also need to verify cases where the user presses the dot button `.`

2021-01-26 08:48 UTC, whiz25 approved these changes
## Approved ✅ 
Nice work @kwizl . You fixed operations in the `operate.js` file as suggested by the previous reviewer. This PR looks good to me. Merge and proceed to the next milestone.


### Martin Afani

2021-01-26 10:18 UTC, merged